---
- name: Install toolchain
  become: true
  become_user: root
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - zlib1g-dev
    - libncurses5-dev
    - libgdbm-dev
    - libnss3-dev
    - libssl-dev
    - libreadline-dev
    - libffi-dev
    - libsqlite3-dev
    - wget
    - libbz2-dev
    - python3
    - python3-pip
    - python3-venv

- name: Install oracle cloud infrastructure CLI
  ansible.builtin.command:
    cmd: pip install --user oci-cli

- name: Configure OCI secrets
  ansible.builtin.command:
    cmd: oci setup repair-file-permissions --file /home/wise/.oci/config
