#!/bin/bash
# Generate considerations for golden image manifest change.
#
# These considerations are generated by comparing the OCI Ubuntu-22.04-minimal package
# manifest with our package manifest.

tempdir=$(mktemp --directory --tmpdir=$HOME)

cut -f1 -d'/' debian.txt | sort > ${tempdir}/debian.list
cut -f1 -d'/' ubuntu.txt | sort > ${tempdir}/ubuntu.list
diff -uNr ${tempdir}/debian.list ${tempdir}/ubuntu.list > ${tempdir}/debian-ubuntu.diff

echo "Consider removing from the default package manifest."
grep "^-" ${tempdir}/debian-ubuntu.diff
echo "Consider adding to the default package manifest."
grep "^+" ${tempdir}/debian-ubuntu.diff

rm -r ${tempdir}
