---
- name: Install gpg
  become: yes
  become_user: root
  ansible.builtin.apt:
    name: gpg
    state: present
    
- name: Install Ansible
  become: yes
  become_user: root
  ansible.builtin.apt:
    name: ansible
