---
- name: Install and Clone Git Repository
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install git
      ansible.builtin.apt:
        name: git
        state: present

    - name: Clone origin main branch
      ansible.builtin.git:
        accept_newhostkey: true
        depth: 1
        repo: "https://github.com/artificialwisdomai/origin"
        dest: "/home/wise/origin"
