---
- name: Install apt-based command line tools
  become: yes
  become_user: root
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - acl
    - git
    - curl
    - mlocate
    - apt-file
    - numactl
    - libhugetlbfs-bin
