---
- name: Setup VirtualBox
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install gpg
      ansible.builtin.apt:
        name: gpg
        state: present

    - name: Install VirtualBox gpg key
      ansible.builtin.apt_key:
        url: "https://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc"
        keyring: "/usr/share/keyrings/oracle-virtualbox-2016.gpg"
        state: present

    - name: Install VirtualBox apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian bullseye contrib"
        update_cache: true
        state: present

    - name: Install VirtualBox tooling
      ansible.builtin.apt:
        name: virtualbox-7.0
        state: present
