apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: vectorindices.new.artificialwisdom.cloud
spec:
    group: new.artificialwisdom.cloud
    versions:
    - name: v1
        storage: true
        served: true
        schema:
            openAPIV3Schema:
                type: object
                properties:
                    status:
                        type: object
                        properties:
                            phase:
                                type: string
                                description: "The phase state of the index."
                    spec:
                        type: object
                        properties:
                            dataset:
                                type: string
                                description: "The name of the DataSet used to build the index."
                            factory:
                                type: string
                                description: "The index factory; see https://github.com/facebookresearch/faiss/wiki/The-index-factory"
    scope: Namespaced
    names:
        plural: vectorindices
        singular: vectorindex
        kind: VectorIndex
        shortNames: ["vi"]
