---
# Fix user setup for packer user

#  lock password to avoid password logins

- name: Lock packer user password to prevent password reset or login
  ansible.builtin.user:
    name: packer
    password: '*'

#  update authorized keys from @sdake and @rstarmer

- name: Set authorized keys for packer user - sdake
  ansible.posix.authorized_key:
    user: packer
    state: present
    key: "{{ lookup('url', 'https://github.com/sdake.keys', split_lines=False) }}"

- name: Set authorized keys for packer user - sdake
  ansible.posix.authorized_key:
    user: packer
    state: present
    key: "{{ lookup('url', 'https://github.com/rstarmer.keys', split_lines=False) }}"

# Update apt package cache and installed packages to latest versions

- name: update apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: true

# Fix grub config to support tty at boot
- name: add iscsi packages
  ansible.builtin.apt:
    name: open-iscsi
    state: present

- name: update grub2 to ensure the network is activated early
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    line: 'GRUB_PRELOAD_MODULES="net_bootp"'

- name: Update grub2 config to support tty at boot
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX ip=dhcp console=tty0 console=ttyS0 netroot=iscsi:@169.254.0.2::::iqn.2015-02.oracle.boot:uefi iscsi_initiator=iqn.2015-02.oracle.boot:instance biosdevname=0"'

- name: Re-install grub2 efi
  ansible.builtin.shell: grub-install --target=x86_64-efi --bootloader-id=debian --recheck --no-floppy

# # This may technically be redundant to the next command
# - name: create grub.cfg boot entry
#   ansible.builtin.shell: grub-mkconfig -o /boot/grub/grub.cfg -o /boot/efi/EFI/debian/grub.cfg

- name: update grub
  ansible.builtin.command: update-grub

