name: Build Docker images

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image & Upload to GHCR
        uses: docker/build-push-action@v5
        with:
          context: workloads/dataset-controller
          push: ${{ github.event_name == 'push' }}
          tags: origin/workloads/dataset-controller:latest
