# https://github.com/marketplace/actions/yaml-lint
---
name: Lint YAML files
on:
  push:
    branches: [ "main" ]   # yamllint disable-line rule:truthy
  pull_request:
    branches: [ "main" ]   # yamllint disable-line rule:truthy

jobs:
  lint_yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: yaml-lint
        uses: ibiqlik/action-yamllint@v3
      - run: echo ${{ steps.yaml-lint.outputs.logfile }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: yamllint-logfile
          path: ${{ steps.yaml-lint.outputs.logfile }}
