# https://github.com/marketplace/actions/github-spellcheck-action

name: Lint links
on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: Check links with linkcheck
    - uses: filiph/linkcheck@2.0.23
      name: linkt-links
