# https://github.com/marketplace/actions/yaml-lint
---
name: Lint YAML files
on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint_yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: ${{ github.workspace }}/.github/config/lint_yaml_config.yml
