---
name: Lint YAML files
on:
  push:
    branches: [ "main" ]   # yamllint disable-line rule:truthy
  pull_request:
    branches: [ "main" ]   # yamllint disable-line rule:truthy

jobs:
  lint_yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
